[package]
version = "0.1.0"
name = "utxo-spend-script"
edition = "2021"
default-run = "utxo-spend"

[[bin]]
name = "utxo-spend"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
sp1-sdk = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
alloy-sol-types = { workspace = true }
utxo-spend-lib = { path = "../lib" }
dotenv = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
