[da]
connection_string = "sqlite:///mnt/rollup-state/mock_da.sqlite?mode=rwc"

sender_address = "0000000000000000000000000000000000000000000000000000000000000000"
finalization_blocks = 0
[da.block_producing.periodic]
block_time_ms = 6_000

[storage]
path = "/mnt/rollup-state/rollup-starter-data-mock"

user_commit_concurrency = 6
kernel_commit_concurrency = 2
pruner_versions_to_keep = 100
user_hashtable_buckets = 1_000_000
user_preallocate_ht = false

[runner]
da_polling_interval_ms = 2_000

[runner.http_config]
bind_host = "0.0.0.0"
bind_port = 12346
public_address = "http://178.156.201.105:12346"

[monitoring]
telegraf_address = "127.0.0.1:8094"

[proof_manager]
aggregated_proof_block_jump = 1
prover_address = "1RE6BqM5276sUrSsvaBKLwrBATUqKPSFxkagUWwcQg6"
max_number_of_transitions_in_db = 100
max_number_of_transitions_in_memory = 20
max_number_of_aggregated_proofs_in_memory = 5

[sequencer]
max_batch_size_bytes = 7340032
max_concurrent_batch_blobs = 128
max_concurrent_proof_blobs = 1024
max_allowed_node_distance_behind = 10
rollup_address = "1RE6BqM5276sUrSsvaBKLwrBATUqKPSFxkagUWwcQg6"
blob_processing_timeout_secs = 60

[sequencer.preferred]
disable_state_root_consistency_checks = true
recovery_strategy = "TryToSave"
batch_execution_time_limit_millis = 6000
ideal_lag_behind_finalized_slot = 1
num_cache_warmup_workers = 0

# Uncomment to enable Postgres for soft confirmations:
# [sequencer.preferred.postgres_config]
# postgres_connection_string = "postgresql://postgres:pass@localhost:5432/db"
# node_role = "Leader"
# node_id = "node_1"

[sequencer.extension]
max_log_limit = 20000
